using System;
using System.Collections.Generic;

namespace FMPI.Marketing.Core.Models
{
    public partial class DeletedRecords
    {
        public decimal SysPkDelRec { get; set; }
        public string StatusDelRec { get; set; }
        public string UserName { get; set; }
        public string OneTimeDeletingRightsGrantedBy { get; set; }
        public string FormCaption { get; set; }
        public DateTime? DateTimeDeleted { get; set; }
        public string RecordInfo { get; set; }
        public decimal? RecordSysPk { get; set; }
        public string TableName { get; set; }
        public string StationNum { get; set; }
        public string Field001 { get; set; }
        public string Field002 { get; set; }
        public string Field003 { get; set; }
        public string Field004 { get; set; }
        public string Field005 { get; set; }
        public string Field006 { get; set; }
        public string Field007 { get; set; }
        public string Field008 { get; set; }
        public string Field009 { get; set; }
        public string Field010 { get; set; }
        public string Field011 { get; set; }
        public string Field012 { get; set; }
        public string Field013 { get; set; }
        public string Field014 { get; set; }
        public string Field015 { get; set; }
        public string Field016 { get; set; }
        public string Field017 { get; set; }
        public string Field018 { get; set; }
        public string Field019 { get; set; }
        public string Field020 { get; set; }
        public string Field021 { get; set; }
        public string Field022 { get; set; }
        public string Field023 { get; set; }
        public string Field024 { get; set; }
        public string Field025 { get; set; }
        public string Field026 { get; set; }
        public string Field027 { get; set; }
        public string Field028 { get; set; }
        public string Field029 { get; set; }
        public string Field030 { get; set; }
        public string Field031 { get; set; }
        public string Field032 { get; set; }
        public string Field033 { get; set; }
        public string Field034 { get; set; }
        public string Field035 { get; set; }
        public string Field036 { get; set; }
        public string Field037 { get; set; }
        public string Field038 { get; set; }
        public string Field039 { get; set; }
        public string Field040 { get; set; }
        public string Field041 { get; set; }
        public string Field042 { get; set; }
        public string Field043 { get; set; }
        public string Field044 { get; set; }
        public string Field045 { get; set; }
        public string Field046 { get; set; }
        public string Field047 { get; set; }
        public string Field048 { get; set; }
        public string Field049 { get; set; }
        public string Field050 { get; set; }
        public string Field051 { get; set; }
        public string Field052 { get; set; }
        public string Field053 { get; set; }
        public string Field054 { get; set; }
        public string Field055 { get; set; }
        public string Field056 { get; set; }
        public string Field057 { get; set; }
        public string Field058 { get; set; }
        public string Field059 { get; set; }
        public string Field060 { get; set; }
        public string Field061 { get; set; }
        public string Field062 { get; set; }
        public string Field063 { get; set; }
        public string Field064 { get; set; }
        public string Field065 { get; set; }
        public string Field066 { get; set; }
        public string Field067 { get; set; }
        public string Field068 { get; set; }
        public string Field069 { get; set; }
        public string Field070 { get; set; }
        public string Field071 { get; set; }
        public string Field072 { get; set; }
        public string Field073 { get; set; }
        public string Field074 { get; set; }
        public string Field075 { get; set; }
        public string Field076 { get; set; }
        public string Field077 { get; set; }
        public string Field078 { get; set; }
        public string Field079 { get; set; }
        public string Field080 { get; set; }
        public string Field081 { get; set; }
        public string Field082 { get; set; }
        public string Field083 { get; set; }
        public string Field084 { get; set; }
        public string Field085 { get; set; }
        public string Field086 { get; set; }
        public string Field087 { get; set; }
        public string Field088 { get; set; }
        public string Field089 { get; set; }
        public string Field090 { get; set; }
        public string Field091 { get; set; }
        public string Field092 { get; set; }
        public string Field093 { get; set; }
        public string Field094 { get; set; }
        public string Field095 { get; set; }
        public string Field096 { get; set; }
        public string Field097 { get; set; }
        public string Field098 { get; set; }
        public string Field099 { get; set; }
        public string Field100 { get; set; }
        public string Field101 { get; set; }
        public string Field102 { get; set; }
        public string Field103 { get; set; }
        public string Field104 { get; set; }
        public string Field105 { get; set; }
        public string Field106 { get; set; }
        public string Field107 { get; set; }
        public string Field108 { get; set; }
        public string Field109 { get; set; }
        public string Field110 { get; set; }
        public string Field111 { get; set; }
        public string Field112 { get; set; }
        public string Field113 { get; set; }
        public string Field114 { get; set; }
        public string Field115 { get; set; }
        public string Field116 { get; set; }
        public string Field117 { get; set; }
        public string Field118 { get; set; }
        public string Field119 { get; set; }
        public string Field120 { get; set; }
        public string Field121 { get; set; }
        public string Field122 { get; set; }
        public string Field123 { get; set; }
        public string Field124 { get; set; }
        public string Field125 { get; set; }
        public string Field126 { get; set; }
        public string Field127 { get; set; }
        public string Field128 { get; set; }
        public string Field129 { get; set; }
        public string Field130 { get; set; }
        public string Field131 { get; set; }
        public string Field132 { get; set; }
        public string Field133 { get; set; }
        public string Field134 { get; set; }
        public string Field135 { get; set; }
        public string Field136 { get; set; }
        public string Field137 { get; set; }
        public string Field138 { get; set; }
        public string Field139 { get; set; }
        public string Field140 { get; set; }
        public string Field141 { get; set; }
        public string Field142 { get; set; }
        public string Field143 { get; set; }
        public string Field144 { get; set; }
        public string Field145 { get; set; }
        public string Field146 { get; set; }
        public string Field147 { get; set; }
        public string Field148 { get; set; }
        public string Field149 { get; set; }
        public string Field150 { get; set; }
        public string Field151 { get; set; }
        public string Field152 { get; set; }
        public string Field153 { get; set; }
        public string Field154 { get; set; }
        public string Field155 { get; set; }
        public string Field156 { get; set; }
        public string Field157 { get; set; }
        public string Field158 { get; set; }
        public string Field159 { get; set; }
        public string Field160 { get; set; }
        public string Field161 { get; set; }
        public string Field162 { get; set; }
        public string Field163 { get; set; }
        public string Field164 { get; set; }
        public string Field165 { get; set; }
        public string Field166 { get; set; }
        public string Field167 { get; set; }
        public string Field168 { get; set; }
        public string Field169 { get; set; }
        public string Field170 { get; set; }
        public string Field171 { get; set; }
        public string Field172 { get; set; }
        public string Field173 { get; set; }
        public string Field174 { get; set; }
        public string Field175 { get; set; }
        public string Field176 { get; set; }
        public string Field177 { get; set; }
        public string Field178 { get; set; }
        public string Field179 { get; set; }
        public string Field180 { get; set; }
        public string Field181 { get; set; }
        public string Field182 { get; set; }
        public string Field183 { get; set; }
        public string Field184 { get; set; }
        public string Field185 { get; set; }
        public string Field186 { get; set; }
        public string Field187 { get; set; }
        public string Field188 { get; set; }
        public string Field189 { get; set; }
        public string Field190 { get; set; }
        public string Field191 { get; set; }
        public string Field192 { get; set; }
        public string Field193 { get; set; }
        public string Field194 { get; set; }
        public string Field195 { get; set; }
        public string Field196 { get; set; }
        public string Field197 { get; set; }
        public string Field198 { get; set; }
        public string Field199 { get; set; }
        public string Field200 { get; set; }
        public string Field201 { get; set; }
        public string Field202 { get; set; }
        public string Field203 { get; set; }
        public string Field204 { get; set; }
        public string Field205 { get; set; }
        public string Field206 { get; set; }
        public string Field207 { get; set; }
        public string Field208 { get; set; }
        public string Field209 { get; set; }
        public string Field210 { get; set; }
        public string Field211 { get; set; }
        public string Field212 { get; set; }
        public string Field213 { get; set; }
        public string Field214 { get; set; }
        public string Field215 { get; set; }
        public string Field216 { get; set; }
        public string Field217 { get; set; }
        public string Field218 { get; set; }
        public string Field219 { get; set; }
        public string Field220 { get; set; }
        public string Field221 { get; set; }
        public string Field222 { get; set; }
        public string Field223 { get; set; }
        public string Field224 { get; set; }
        public string Field225 { get; set; }
        public string Field226 { get; set; }
        public string Field227 { get; set; }
        public string Field228 { get; set; }
        public string Field229 { get; set; }
        public string Field230 { get; set; }
        public string Field231 { get; set; }
        public string Field232 { get; set; }
        public string Field233 { get; set; }
        public string Field234 { get; set; }
        public string Field235 { get; set; }
        public string Field236 { get; set; }
        public string Field237 { get; set; }
        public string Field238 { get; set; }
        public string Field239 { get; set; }
        public string Field240 { get; set; }
        public string Field241 { get; set; }
        public string Field242 { get; set; }
        public string Field243 { get; set; }
        public string Field244 { get; set; }
    }
}
