using System;
using System.Collections.Generic;

namespace FMPI.Marketing.Core.Models
{
    public partial class TransactionPayrollPaySlip
    {
        public decimal SysPkPayrlPslp { get; set; }
        public decimal SysFkTransHPayrlPslp { get; set; }
        public decimal SysFkUmemplPayrlPslp { get; set; }
        public decimal SysFkPlcyRatePayrlPslp { get; set; }
        public decimal SysFkUmbranchPayrlPslp { get; set; }
        public decimal SysFkPmdeductPayrlPslp { get; set; }
        public decimal SysFkCoapayPayrlPslp { get; set; }
        public short? SysSeqPayrlPslp { get; set; }
        public int? UserSeqPayrlPslp { get; set; }
        public string UserPkPayrlPslp { get; set; }
        public string LastUpdatedByPayrlPslp { get; set; }
        public short? LastUpdatedConcurrencyIdPayrlPslp { get; set; }
        public DateTime? LastUpdatedDatePayrlPslp { get; set; }
        public string ModulePayrlPslp { get; set; }
        public decimal? AmountGrossPayrlPslp { get; set; }
        public decimal? AmountNetPayrlPslp { get; set; }
        public decimal? AmountDeductionPayrlPslp { get; set; }
        public decimal? AmountAdditionPayrlPslp { get; set; }
        public string BranchcodePayrlPslp { get; set; }
        public decimal? RegularDayWorkPayrlPslp { get; set; }
        public DateTime? DatePayrlPslp { get; set; }
        public decimal? DaysAbsentPayrlPslp { get; set; }
        public decimal? AbsentRatePayrlPslp { get; set; }
        public decimal? HoursPerDayPayrlPslp { get; set; }
        public decimal? TotalAbsentChargePayrlPslp { get; set; }
        public string RateCodePayrlPslp { get; set; }
        public decimal? RegularDayRatePayrlPslp { get; set; }
        public decimal? RegularHourWorkPayrlPslp { get; set; }
        public decimal? RegularMonthRatePayrlPslp { get; set; }
        public decimal? RegularHourRatePayrlPslp { get; set; }
        public decimal? RegularPieceWorkPayrlPslp { get; set; }
        public decimal? RegularPieceRatePayrlPslp { get; set; }
        public decimal? RegularWagePayrlPslp { get; set; }
        public string RateMethodPayrlPslp { get; set; }
        public decimal? TotalDaysWorkedPayrlPslp { get; set; }
        public decimal? IncomeTaxAmountPayrlPslp { get; set; }
        public decimal? WithHoldingTaxAmountPayrlPslp { get; set; }
        public decimal? PagibigLoanPayrlPslp { get; set; }
        public decimal? PagibigContErPayrlPslp { get; set; }
        public decimal? PagibigContEePayrlPslp { get; set; }
        public decimal? ShortDeductionPayrlPslp { get; set; }
        public decimal? CashAdvancePayrlPslp { get; set; }
        public decimal? SsscontEePayrlPslp { get; set; }
        public decimal? SsscontErPayrlPslp { get; set; }
        public decimal? SssloanPayrlPslp { get; set; }
        public decimal? PhilHealthAmountPayrlPslp { get; set; }
        public decimal? Deduction1PayrlPslp { get; set; }
        public decimal? Deduction2PayrlPslp { get; set; }
        public decimal? Deduction3PayrlPslp { get; set; }
        public decimal? Deduction4PayrlPslp { get; set; }
        public decimal? TotalLatesChargePayrlPslp { get; set; }
        public decimal? LatesRatePayrlPslp { get; set; }
        public decimal? LatesPayrlPslp { get; set; }
        public decimal? Overtime1DayRatePayrlPslp { get; set; }
        public decimal? Overtime1DayWorkPayrlPslp { get; set; }
        public decimal? Overtime1HourRatePayrlPslp { get; set; }
        public decimal? Overtime1HourWorkPayrlPslp { get; set; }
        public decimal? Overtime1WagePayrlPslp { get; set; }
        public decimal? Overtime2DayRatePayrlPslp { get; set; }
        public decimal? Overtime2DayWorkPayrlPslp { get; set; }
        public decimal? Overtime2HourRatePayrlPslp { get; set; }
        public decimal? Overtime2HourWorkPayrlPslp { get; set; }
        public decimal? Overtime2WageHourPayrlPslp { get; set; }
        public decimal? Overtime2WageDayPayrlPslp { get; set; }
        public decimal? Overtime3DayRatePayrlPslp { get; set; }
        public decimal? Overtime3DayWorkPayrlPslp { get; set; }
        public decimal? Overtime3HourRatePayrlPslp { get; set; }
        public decimal? Overtime3HourWorkPayrlPslp { get; set; }
        public decimal? Overtime3WagePayrlPslp { get; set; }
        public decimal? UndertimePayrlPslp { get; set; }
        public decimal? UndertimeTotalChargePayrlPslp { get; set; }
        public decimal? UndertimeRatePayrslp { get; set; }
        public decimal? TotalDaysOfWorkPayrlPslp { get; set; }
        public decimal? TotalHoursOfWorkPayrlPslp { get; set; }
        public decimal? TotalMinsOfWorkPayrlPslp { get; set; }
        public decimal? TotalOtdaysOfWorkPayrlPslp { get; set; }
        public decimal? TotalOthoursOfWorkPayrlPslp { get; set; }
        public decimal? TotalOtminsOfWorkPayrlPslp { get; set; }
        public decimal? TotalLegalHolidaysHoursOtPayrlPslp { get; set; }
        public decimal? TotalLegalHolidaysMinsOtPayrlPslp { get; set; }
        public decimal? TotalLegalHolidaysOtPayrlPslp { get; set; }
        public decimal? LegalHolidayRatePayrlPslp { get; set; }
        public decimal? LegalHolidayTotalPayrlPslp { get; set; }
        public decimal? TotalSpecialHolidaysHoursOtPayrlPslp { get; set; }
        public decimal? TotalSpecialHolidaysMinsOtPayrlPslp { get; set; }
        public decimal? TotalSpecialHolidaysOtPayrlPslp { get; set; }
        public decimal? SpecialHolidayRatePayrlPslp { get; set; }
        public decimal? SpecialHolidayTotalPayrlPslp { get; set; }
        public decimal? OtratePayrlPslp { get; set; }
        public decimal? TotalWagePayrlPslp { get; set; }
        public decimal? TotalOtwagePayrlPslp { get; set; }
        public string StatusPayrlPslp { get; set; }
        public string TypePayrlPslp { get; set; }
        public int? IsFixedRatedPayrlPslp { get; set; }
        public int? RatePayrlPslp { get; set; }
        public decimal? BalancesPayrlPslp { get; set; }
        public decimal? OverDraftPayrlPslp { get; set; }
    }
}
