using System;
using System.Collections.Generic;

namespace FMPI.Marketing.Core.Models
{
    public partial class TransactionHeaderLoans2
    {
        public decimal SysPkTransHloan { get; set; }
        public decimal SysFkBankTransHloan { get; set; }
        public decimal SysFkCoMaker1TransHloan { get; set; }
        public decimal SysFkCoMaker2TransHloan { get; set; }
        public decimal SysFkLdgrEntryInterestDeductForAccountOfTransHloan { get; set; }
        public decimal SysFkLdgrEntryInterestLoanPaymentsTransHloan { get; set; }
        public decimal SysFkLdgrEntryPrincipalDeductForAccountOfTransHloan { get; set; }
        public decimal SysFkLdgrEntryPrincipalLoanPaymentsTransHloan { get; set; }
        public decimal SysFkLdgrEntrySlprincipalLoanPaymentsTransHloan { get; set; }
        public decimal SysFkPmTransHloan { get; set; }
        public decimal SysFkPmloanTransHloan { get; set; }
        public decimal SysFkPrincipalAuthorityTransHloan { get; set; }
        public decimal SysFkTransHTransHloan { get; set; }
        public decimal SysFkUminsuranceTransHloan { get; set; }
        public short? SysSeqTransHloan { get; set; }
        public int? UserSeqTransHloan { get; set; }
        public string LastUpdatedByTransHloan { get; set; }
        public short? LastUpdatedConcurrencyIdTransHloan { get; set; }
        public DateTime? LastUpdatedDateTransHloan { get; set; }
        public string UserPkAlternative { get; set; }
        public string UserFkBankTransHloan { get; set; }
        public string UserFkCoMaker1TransHloan { get; set; }
        public string UserFkCoMaker2TransHloan { get; set; }
        public string UserFkPmTransHloan { get; set; }
        public string UserFkPmloanTransHloan { get; set; }
        public string UserFkPrincipalAuthorityTransHloan { get; set; }
        public string UserFkTransHdeductForAccountOfTransHloan { get; set; }
        public string UserFkTransHpreviousLoanPaymentsTransHloan { get; set; }
        public string UserFkUminsuranceTransHloan { get; set; }
        public string ModuleTransHloan { get; set; }
        public string ModuleTypeTransHloan { get; set; }
        public short? AllowDebitOffsetTransHloan { get; set; }
        public string AreaTransHloan { get; set; }
        public decimal? ArrearsAmountTransHloan { get; set; }
        public DateTime? ArrearsAsOfTransHloan { get; set; }
        public DateTime? BorrowerBirthdateTransHloan { get; set; }
        public string BorrowerBusinessAddressTransHloan { get; set; }
        public DateTime? BorrowerCtcdateIssueTransHloan { get; set; }
        public string BorrowerCtcnumTransHloan { get; set; }
        public string BorrowerCtcplaceIssueTransHloan { get; set; }
        public string BorrowerPostalAddressTransHloan { get; set; }
        public string BorrowerSpadescriptionTransHloan { get; set; }
        public decimal? CardApperPcTransHloan { get; set; }
        public string CardCommissionAmountTransHloan { get; set; }
        public decimal? CardCommissionRateTransHloan { get; set; }
        public decimal? CardCostPerPcTransHloan { get; set; }
        public decimal? CardFaceValuePerPcTransHloan { get; set; }
        public decimal? CardIncomePerPcTransHloan { get; set; }
        public decimal? CardQtyTransHloan { get; set; }
        public decimal? CardSellingPerPcTransHloan { get; set; }
        public decimal? CashReleasedTansHloan { get; set; }
        public DateTime? CheckDateTransHloan { get; set; }
        public string CheckNumTransHloan { get; set; }
        public DateTime? CoMaker1CtcdateIssueTransHloan { get; set; }
        public string CoMaker1CtcnumTransHloan { get; set; }
        public string CoMaker1CtcplaceIssueTransHloan { get; set; }
        public string CoMaker1AddressPostalTransHloan { get; set; }
        public decimal? CoMaker1AmountCreditLineTransHloan { get; set; }
        public decimal? CoMaker1AmountCurrentArTransHloan { get; set; }
        public decimal? CoMaker1AmountGuaranteedTransHloan { get; set; }
        public DateTime? CoMaker1BirthDateTransHloan { get; set; }
        public string CoMaker1NameTransHloan { get; set; }
        public string CoMaker1RelationshipTransHloan { get; set; }
        public string CoMaker1TinTransHloan { get; set; }
        public string CoMaker2AddressPostalTransHloan { get; set; }
        public decimal? CoMaker2AmountCreditLineTransHloan { get; set; }
        public decimal? CoMaker2AmountCurrentArTransHloan { get; set; }
        public decimal? CoMaker2AmountGuaranteedTransHloan { get; set; }
        public DateTime? CoMaker2BirthDateTransHloan { get; set; }
        public DateTime? CoMaker2CtcdateIssueTransHloan { get; set; }
        public string CoMaker2CtcnumTransHloan { get; set; }
        public string CoMaker2CtcplaceIssueTransHloan { get; set; }
        public string CoMaker2NameTransHloan { get; set; }
        public string CoMaker2RelationshipTransHloan { get; set; }
        public string CoMaker2TinTransHloan { get; set; }
        public decimal? DailySavingsTransHloan { get; set; }
        public DateTime? DateDueTransHloan { get; set; }
        public DateTime? DateFirstPaymentOnTransHloan { get; set; }
        public string EnterpriseTransHloan { get; set; }
        public short? GracePeriodInDaysPastDueBeforePenaltyChargesTransHloan { get; set; }
        public decimal? HandlingFeeTransHloan { get; set; }
        public decimal? InsuranceFeeTransHloan { get; set; }
        public decimal? InterestAdvancePaymentsTransHloan { get; set; }
        public string InterestComputationMethodTransHloan { get; set; }
        public decimal? InterestCurrentLoanTransHloan { get; set; }
        public decimal? InterestDeductForAccountOfTransHloan { get; set; }
        public string InterestPaymentFrequencyTransHloan { get; set; }
        public decimal? InterestPreviousLoanPaymentsTransHloan { get; set; }
        public decimal? InterestRateEntireTermTransHloan { get; set; }
        public decimal? InterestRateMonthlyTransHloan { get; set; }
        public decimal? InterestRateSimpleAnnualRateTransHloan { get; set; }
        public decimal? InterestUsualDueDailyTransHloan { get; set; }
        public decimal? InterestUsualDueMonthlyTransHloan { get; set; }
        public decimal? InterestUsualDueWeeklyTransHloan { get; set; }
        public short? LoanCountTransHloan { get; set; }
        public decimal? LoanReceivableAdvancePaymentsTransHloan { get; set; }
        public decimal? LoanReceivableCurrentLoanTransHloan { get; set; }
        public decimal? LoanReceivablePreviousLoanPaymentsTransHloan { get; set; }
        public decimal? MembershipFeeTransHloan { get; set; }
        public decimal? MiscExpensesTransHloan { get; set; }
        public decimal? MoafeeTransHloan { get; set; }
        public decimal? MortgageAmountTransHloan { get; set; }
        public string MortgageByVirtueOfTransHloan { get; set; }
        public string MortgageItemDescriptionTransHloan { get; set; }
        public string MortgageItemPictureFileNameTransHloan { get; set; }
        public decimal? NotarialFeeTransHloan { get; set; }
        public short? NumOfTimesReloanTransHloan { get; set; }
        public decimal? OtherChargesTransHloan { get; set; }
        public decimal? PrincipalAdvancePaymentsTransHloan { get; set; }
        public string PrincipalAuthorityBirthdateTransHloan { get; set; }
        public DateTime? PrincipalAuthorityCtcdateIssueTransHloan { get; set; }
        public string PrincipalAuthorityCtcnumTransHloan { get; set; }
        public string PrincipalAuthorityCtcplaceIssueTransHloan { get; set; }
        public string PrincipalAuthorityNameTransHloan { get; set; }
        public string PrincipalAuthorityPostalAddressTransHloan { get; set; }
        public string PrincipalAuthorityRelationshipTransHloan { get; set; }
        public string PrincipalAuthoritySpadescriptionTransHloan { get; set; }
        public string PrincipalAuthorityTinTransHloan { get; set; }
        public decimal? PrincipalCurrentLoanTransHloan { get; set; }
        public decimal? PrincipalDeductForAccountOfTransHloan { get; set; }
        public string PrincipalPaymentFrequencyTransHloan { get; set; }
        public decimal? PrincipalUsualDueDailyTransHloan { get; set; }
        public decimal? PrincipalUsualDueMonthlyTransHloan { get; set; }
        public decimal? PrincipalUsualDueWeeklyTransHloan { get; set; }
        public decimal? PrincipalPreviousLoanPaymentsTransHloan { get; set; }
        public decimal? ShareCapitalAsOfAppliedDateTransHloan { get; set; }
        public decimal? ShareCapitalRefundTransHloan { get; set; }
        public decimal? ShareCapitalRetainedTransHloan { get; set; }
        public string ShareCapitalRetainedRateTransHloan { get; set; }
        public decimal? SavingsAsOfAppliedDateTransHloan { get; set; }
        public decimal? SavingsRetainedTransHloan { get; set; }
        public string SavingsRetainedRateTransHloan { get; set; }
        public short? TermsInDaysTransHloan { get; set; }
        public short? TermsInMonthsTransHloan { get; set; }
        public short? TermsInYearsTransHloan { get; set; }
        public decimal? TotalAdvancePaymentsTransHloan { get; set; }
        public decimal? TotalDeductionsTransHloan { get; set; }
        public decimal? TotalDeductForAccountOfTransHloan { get; set; }
        public decimal? TotalFinanceChargesTransHloan { get; set; }
        public decimal? TotalOffsetAmountTransHloan { get; set; }
        public decimal? TotalOffsetDramountTransHloan { get; set; }
        public decimal? TotalPreviousLoanPaymentsTransHloan { get; set; }
        public decimal? TotalUsualDueDailyTransHloan { get; set; }
        public decimal? TotalUsualDueMonthlyTransHloan { get; set; }
        public decimal? TotalUsualDueWeeklyTransHloan { get; set; }
    }
}
