using System;
using System.Collections.Generic;

namespace FMPI.Marketing.Core.Models
{
    public partial class TransactionLedgerInvtyLog
    {
        public decimal SysPkLdgrInvty { get; set; }
        public decimal SysFkCustomerLdgrInvty { get; set; }
        public decimal SysFkDeptLdgrInvty { get; set; }
        public decimal SysFkInvtyLdgrInvty { get; set; }
        public decimal SysFkInvtyBatchLdgrInvty { get; set; }
        public decimal SysFkInvtyUnitMsrLdgrInvty { get; set; }
        public decimal SysFkInvtyPriceLdgrInvty { get; set; }
        public decimal SysFkLedgerLdgrInvty { get; set; }
        public decimal SysFkSectionLdgrInvty { get; set; }
        public decimal SysFkSourceDocumentLdgrInvty { get; set; }
        public decimal SysFkSupplierLdgrInvty { get; set; }
        public decimal SysFkTransHLdgrInvty { get; set; }
        public decimal SysFkWarehouseLdgrInvty { get; set; }
        public short? SysSeqLdgrInvty { get; set; }
        public int? UserSeqLdgrInvty { get; set; }
        public string UserPkLdgrInvty { get; set; }
        public string UserFkInvtyLdgrInvty { get; set; }
        public string UserFkInvtyBatchLdgrInvty { get; set; }
        public string UserFkInvtyPriceLdgrInvty { get; set; }
        public string UserFkLaneLdgrInvty { get; set; }
        public string UserFkTankLdgrInvty { get; set; }
        public string UserFksourceDocumentLdgrInvty { get; set; }
        public string UserPkalternativeLdgrInvty { get; set; }
        public string UserPkcustomerLdgrInvty { get; set; }
        public string UserPkpriceLdgrInvty { get; set; }
        public string UserPksupplierLdgrInvty { get; set; }
        public string UserPktransHLdgrInvty { get; set; }
        public string UserPkwarehouseLdgrInvty { get; set; }
        public string LastUpdatedByLdgrInvty { get; set; }
        public short? LastUpdatedConcurrencyIdLdgrInvty { get; set; }
        public DateTime? LastUpdatedDateLdgrInvty { get; set; }
        public string ModuleLdgrInvty { get; set; }
        public decimal? AdditionalQtyLdgrInvty { get; set; }
        public decimal? ArqtyLdgrInvty { get; set; }
        public decimal? ArsubTotalLdgrInvty { get; set; }
        public string BarcodeLdgrInvty { get; set; }
        public decimal? BaseUnitAccumulatedQtyInLdgrInvty { get; set; }
        public decimal? BaseUnitAccumulatedQtyOutLdgrInvty { get; set; }
        public decimal? BaseUnitAccumulatedQtyBalanceLdgrInvty { get; set; }
        public decimal? BaseUnitQtyAdjustLdgrInvty { get; set; }
        public decimal? BaseUnitQtyInLdgrInvty { get; set; }
        public string BaseUnitOfMeasureLdgrInvty { get; set; }
        public decimal? BaseUnitQtyMultiplierLdgrInvty { get; set; }
        public decimal? BaseUnitQtyOutLdgrInvty { get; set; }
        public decimal? BaseUnitQtyRunBalPerInvtyLdgrInvty { get; set; }
        public decimal? BaseUnitQtyRunBalPerWarehouseLdgrInvty { get; set; }
        public decimal? CashQtyLdgrInvty { get; set; }
        public decimal? CashSubTotalLdgrInvty { get; set; }
        public string CheckedByLdgrInvty { get; set; }
        public decimal? ClosingQtyLdgrInvty { get; set; }
        public string CommissionRateLdgrInvty { get; set; }
        public decimal? CommissionAmountLdgrInvty { get; set; }
        public decimal? ComputedQtyOutLdgrInvty { get; set; }
        public decimal? ComputedSubTotalOutLdgrInvty { get; set; }
        public decimal? ConsignActualBeginningConsignedQtyLdgrInvty { get; set; }
        public decimal? ConsignActualConsignedQtyLdgrInvty { get; set; }
        public decimal? ConsignDiscrepancyBeginningConsignedQtyLdgrInvty { get; set; }
        public decimal? ConsignDiscrepancyConsignedQtyLdgrInvty { get; set; }
        public decimal? ConsignDisplayedActualSoldLdgrInvty { get; set; }
        public decimal? ConsignDisplayedAdditionalConsignedQtyLdgrInvty { get; set; }
        public decimal? ConsignDisplayedBeginningConsignedQtyLdgrInvty { get; set; }
        public decimal? ConsignDisplayedConsignedQtyLdgrInvty { get; set; }
        public decimal? ConsignDisplayedDeclaredSoldLdgrInvty { get; set; }
        public decimal? ConsignDisplayedEndConsignedQtyLdgrInvty { get; set; }
        public decimal? ConsignDisplayedOutstandingLdgrInvty { get; set; }
        public decimal? ConsignDisplayedReturnedLdgrInvty { get; set; }
        public decimal? ConsignDisplayedSoldLdgrInvty { get; set; }
        public decimal? ConsignFromSupplierLdgrInvty { get; set; }
        public decimal? ConsignFromSupplierReturnedLdgrInvty { get; set; }
        public decimal? ConsignFromSupplierSoldLdgrInvty { get; set; }
        public decimal? ConsignPhysicalCountQtyLdgrInvty { get; set; }
        public decimal? ConsignRrqtyAdjustLdgrInvty { get; set; }
        public decimal? ConsignRrqtyInLdgrInvty { get; set; }
        public decimal? ConsignRrqtyOutLdgrInvty { get; set; }
        public decimal? ConsignRrqtySoldLdgrInvty { get; set; }
        public decimal? ConsignRrsubTotalAdjustLdgrInvty { get; set; }
        public decimal? ConsignRrsubTotalInLdgrInvty { get; set; }
        public decimal? ConsignRrsubTotalOutLdgrInvty { get; set; }
        public decimal? ConsignRrsubTotalSoldLdgrInvty { get; set; }
        public decimal? ConsignSalesQtyAdjustLdgrInvty { get; set; }
        public decimal? ConsignSalesQtyInLdgrInvty { get; set; }
        public decimal? ConsignSalesQtyOutLdgrInvty { get; set; }
        public decimal? ConsignSalesQtySoldLdgrInvty { get; set; }
        public decimal? ConsignSalesSubTotalAdjustLdgrInvty { get; set; }
        public decimal? ConsignSalesSubTotalInLdgrInvty { get; set; }
        public decimal? ConsignSalesSubTotalOutLdgrInvty { get; set; }
        public decimal? ConsignSalesSubTotalSoldLdgrInvty { get; set; }
        public decimal? ConsignToCustomerLdgrInvty { get; set; }
        public decimal? ConsignToCustomerReturnedLdgrInvty { get; set; }
        public decimal? ConsignToCustomerSoldLdgrInvty { get; set; }
        public DateTime? DateTimeFristReleasedLdgrInvty { get; set; }
        public DateTime? DateTimeLastReceivedLdgrInvty { get; set; }
        public string DeptUserFkLdgrInvty { get; set; }
        public decimal? DiscountedUnitSellingLdgrInvty { get; set; }
        public decimal? DiscountedUnitPurchaseLdgrInvty { get; set; }
        public string DisplayDescriptionLdgrInvty { get; set; }
        public string DisplayDiscountingLdgrInvty { get; set; }
        public decimal? DisplayForeignConversionRateLdgInvty { get; set; }
        public string DisplayForeignSignLdgrInvty { get; set; }
        public decimal? DisplayForeignUnitSellingLdgrInvty { get; set; }
        public decimal? DisplayForeignUnitPurchaseLdgrInvty { get; set; }
        public decimal? DisplayQtyAdjustLdgrInvty { get; set; }
        public decimal? DisplayQtyInLdgrInvty { get; set; }
        public decimal? DisplayQtyOutLdgrInvty { get; set; }
        public decimal? DisplaySubTotalAdjustLdgrInvty { get; set; }
        public decimal? DisplaySubTotalInLdgrInvty { get; set; }
        public decimal? DisplaySubTotalOutLdgrInvty { get; set; }
        public string DisplayUnitOfMeasureLdgrInvty { get; set; }
        public decimal? DisplayUnitPurchaseLdgrInvty { get; set; }
        public decimal? DisplayUnitSellingLdgrInvty { get; set; }
        public decimal? ExpensesQtyLdgrInvty { get; set; }
        public decimal? ExpensesSubTotalLdgrInvty { get; set; }
        public string FormulaUsedInSubTotalLdgrInvty { get; set; }
        public string InChargeByLdgrInvty { get; set; }
        public string InventoryFlagLdgrInvty { get; set; }
        public string InventoryModuleLdgrInvty { get; set; }
        public short? IsConsignedOnPurchaseLdgrInvty { get; set; }
        public short? IsPendingLdgrInvty { get; set; }
        public short? IsPostedToConsignRrLdgrInvty { get; set; }
        public short? IsPostedToConsignSalesLdgrInvty { get; set; }
        public string ManualComputedSubTotalLdgrInvty { get; set; }
        public decimal? OpeningQtyLdgrInvty { get; set; }
        public decimal? OrderedBaseQtyLdgrInvty { get; set; }
        public decimal? OrderedDisplayQtyLdgrInvty { get; set; }
        public string ParticularsLdgrInvty { get; set; }
        public decimal? PurchConsignQtyCreditLdgrInvty { get; set; }
        public decimal? PurchConsignQtyDebitLdgrInvty { get; set; }
        public decimal? RequestedBaseQtyLdgrInvty { get; set; }
        public decimal? RequestedDisplayQtyLdgrInvty { get; set; }
        public decimal? SalesConsignQtyCreditLdgrInvty { get; set; }
        public decimal? SalesConsignQtyDebitLdgrInvty { get; set; }
        public string SectionUserFkLdgrInvty { get; set; }
        public string SerialsLdgrInvty { get; set; }
        public decimal? StockOutQtyLdgrInvty { get; set; }
        public decimal? StockOutSubTotalLdgrInvty { get; set; }
        public decimal? StoreQtyInLdgrInvty { get; set; }
        public decimal? StoreQtyOutLdgrInvty { get; set; }
        public decimal? StoreQtyAdjustLdgrInvty { get; set; }
        public decimal? TotalHoursDifferenceLdgrInvty { get; set; }
        public string TransactionStatusLdgrInvty { get; set; }
        public string TransactionTypeLdgrInvty { get; set; }
        public decimal? UnitNetCostLdgrInvty { get; set; }
        public string UserFkWrseLdgrInvty { get; set; }
        public decimal? DisplayQtyServedLdgrInvty { get; set; }
        public decimal? ForeignDiscountedUnitSellingLdgrInvty { get; set; }
        public decimal? ForeignSubTotalOutLdgrInvty { get; set; }
        public decimal? SysFkLdgrInvtySysPkLdgrInvty { get; set; }
        public decimal? BaseUnitQtyLogLdgrInvty { get; set; }
    }
}
